version: '3'

services:
  connor:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - rabbit
    depends_on:
      - rabbit
    environment:
      - AMQP_HOST=rabbit
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
